/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.adk.kt.types

import kotlinx.serialization.Serializable

/**
 * Code generated by the model to be executed. Produced when the code-execution tool is used,
 * alongside a matching [CodeExecutionResult].
 */
@Serializable
data class ExecutableCode(
  /** The code to be executed. */
  val code: String? = null,
  /** The programming language of the [code]. */
  val language: Language? = null,
  /** A unique identifier the server echoes back on the matching [CodeExecutionResult]. */
  val id: String? = null,
)
