/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.adk.kt.types

import com.google.adk.kt.annotations.AdkJavaInteropApi
import com.google.adk.kt.ids.Uuid
import kotlin.jvm.JvmStatic
import kotlinx.serialization.Contextual
import kotlinx.serialization.EncodeDefault
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonNames

/**
 * Represents a function call in a generation response.
 *
 * @property name The name of the function to call.
 * @property args The arguments to pass to the function.
 * @property id The unique identifier for this function call.
 * @property partialArgs Partial argument fragments being streamed from the model.
 * @property willContinue Whether more partial fragments for this function call are expected.
 */
@Serializable
data class FunctionCall(
  val name: String = "",
  // Always emit args (even empty {}) to match the genai/Python golden shape.
  @EncodeDefault(EncodeDefault.Mode.ALWAYS) val args: Map<String, @Contextual Any?> = emptyMap(),
  val id: String? = null,
  @JsonNames("partial_args") val partialArgs: List<PartialArg>? = null,
  @JsonNames("will_continue") val willContinue: Boolean? = null,
) {
  /**
   * Fluent builder for [FunctionCall], provided primarily for Java callers. Any property left unset
   * falls back to the same default as the constructor.
   */
  @AdkJavaInteropApi
  @Suppress("ScopeReceiverThis") // Java-style builder for Java interop.
  class Builder {
    private var name: String = ""
    private var args: Map<String, Any?> = emptyMap()
    private var id: String? = null
    private var partialArgs: List<PartialArg>? = null
    private var willContinue: Boolean? = null

    fun name(name: String): Builder = apply { this.name = name }

    fun args(args: Map<String, Any?>): Builder = apply { this.args = args }

    fun id(id: String?): Builder = apply { this.id = id }

    fun partialArgs(partialArgs: List<PartialArg>?): Builder = apply {
      this.partialArgs = partialArgs
    }

    fun willContinue(willContinue: Boolean?): Builder = apply { this.willContinue = willContinue }

    fun build(): FunctionCall =
      FunctionCall(
        name = name,
        args = args,
        id = id,
        partialArgs = partialArgs,
        willContinue = willContinue,
      )
  }

  companion object {
    /** Prefix for client-side function call IDs generated by the ADK. */
    const val ADK_FUNCTION_CALL_ID_PREFIX = "adk-"

    /** Function name for requesting user confirmation for a tool execution. */
    const val REQUEST_CONFIRMATION_FUNCTION_CALL_NAME = "adk_request_confirmation"

    /** Key used in the arguments map to store the original function call being confirmed. */
    internal const val ORIGINAL_FUNCTION_CALL_KEY = "originalFunctionCall"

    /** Key used in the arguments map to store the tool confirmation result. */
    internal const val TOOL_CONFIRMATION_KEY = "toolConfirmation"

    /** Key for the function name in the serialized function call map. */
    internal const val NAME_KEY = "name"

    /** Key for the function arguments in the serialized function call map. */
    internal const val ARGS_KEY = "args"

    /** Key for the function call ID in the serialized function call map. */
    internal const val ID_KEY = "id"

    /** Generates a new unique client function call ID prefixed with ADK identifier. */
    fun generateId(): String {
      return "$ADK_FUNCTION_CALL_ID_PREFIX${Uuid.random()}"
    }

    @AdkJavaInteropApi @JvmStatic fun builder(): Builder = Builder()
  }
}
