/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.adk.kt.runners

import com.google.adk.kt.agents.BaseAgent
import com.google.adk.kt.agents.ResumabilityConfig
import com.google.adk.kt.agents.RunConfig
import com.google.adk.kt.artifacts.ArtifactService
import com.google.adk.kt.events.Event
import com.google.adk.kt.memory.MemoryService
import com.google.adk.kt.plugins.PluginManager
import com.google.adk.kt.sessions.SessionService
import com.google.adk.kt.types.Content
import com.google.adk.kt.workflow.Node
import kotlinx.coroutines.flow.Flow

/** The Runner interface defines the contract for running agents. */
interface Runner : AutoCloseable {
  val appName: String

  /**
   * The agent this runner runs. For a node-rooted runner this is a NodeViewAgent over the running
   * node.
   */
  val agent: BaseAgent

  /**
   * The node this runner runs, set when rooted on a node graph. The go-forward field; once [agent]
   * is removed it holds the running unit for every runner.
   */
  val node: Node?
    get() = null

  val sessionService: SessionService
  val artifactService: ArtifactService?
  val memoryService: MemoryService?
  val pluginManager: PluginManager
  val resumabilityConfig: ResumabilityConfig

  /**
   * Main entry method to run the agent in this runner asynchronously.
   *
   * @param userId The user ID of the session.
   * @param sessionId The session ID of the session.
   * @param invocationId The invocation ID of the session, set this to resume an interrupted
   *   invocation.
   * @param newMessage A new message to append to the session.
   * @param stateDelta Optional state changes to apply to the session.
   * @param runConfig The run config for the agent.
   * @return The events generated by the agent.
   */
  fun runAsync(
    userId: String,
    sessionId: String,
    invocationId: String? = null,
    newMessage: Content? = null,
    stateDelta: Map<String, Any>? = null,
    runConfig: RunConfig? = null,
  ): Flow<Event>

  /**
   * Sync interface for local testing and convenience purpose.
   *
   * @param userId The user ID of the session.
   * @param sessionId The session ID of the session.
   * @param newMessage A new message to append to the session.
   * @param runConfig The run config for the agent.
   * @return The events generated by the agent.
   */
  fun run(
    userId: String,
    sessionId: String,
    newMessage: Content,
    runConfig: RunConfig? = null,
  ): Iterator<Event>

  /**
   * Rewinds the session to before the specified invocation.
   *
   * Appends a synthetic user-authored event with reversing `stateDelta` and `artifactDelta` entries
   * that restore session state and artifacts to what they were at the start of
   * [rewindBeforeInvocationId]. State and artifact keys prefixed with `app:` and `user:` are
   * preserved (they outlive the rewound invocation). Mirrors Python ADK `runners.py:rewind_async`.
   *
   * The default implementation throws [NotImplementedError] for temporary backward compatibility
   * with existing [Runner] implementations; override to support session rewind.
   *
   * @param userId The user ID of the session.
   * @param sessionId The session ID of the session.
   * @param rewindBeforeInvocationId The invocation to rewind before.
   * @throws IllegalArgumentException if no event in the session has the given invocation id.
   */
  suspend fun rewindAsync(userId: String, sessionId: String, rewindBeforeInvocationId: String) {
    throw NotImplementedError("rewindAsync for ${this::class.simpleName} is not implemented")
  }

  /**
   * Releases resources held by this runner, such as its plugins and the toolsets its agents own.
   *
   * Being [AutoCloseable] lets callers manage a runner's lifecycle idiomatically, e.g. with
   * Kotlin's `use {}`. See [AbstractRunner.close] for the standard behavior.
   */
  override fun close()
}
